---
- name: Check Execution Environment Python and packages
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Show Python version
      command: python3 --version
      register: py_ver

    - debug:
        var: py_ver.stdout

    - name: Check installed pip packages
      command: python3 -m pip list
      register: pip_output

    - debug:
        var: pip_output.stdout_lines
